# Generated by Django 4.2.6 on 2023-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_library', '0001_initial'),
        ('book', '0001_initial'),
        ('api', '0002_userprofileinfo_bying_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bying_book',
            field=models.ManyToManyField(blank=True, null=True, to='book.allbook'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bying_genaral_book',
            field=models.ManyToManyField(blank=True, null=True, to='general_library.librarybook'),
        ),
    ]
