# Generated by Django 4.2.6 on 2023-10-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='page',
            name='book',
        ),
        migrations.AddField(
            model_name='allbook',
            name='chapter',
            field=models.ManyToManyField(blank=True, to='book.chapter'),
        ),
    ]
