# Generated by Django 4.2.6 on 2023-10-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBookPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_library.librarybookpublisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('page_number', models.CharField(blank=True, max_length=100, null=True)),
                ('page_images', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_library.librarybook')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_library.bookchapter')),
            ],
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_library.librarybook'),
        ),
    ]
